language: cpp
sudo: true
matrix:
  include:

  - os: osx
    compiler: clang

  - os: linux
    compiler: gcc
    addons:
      apt:
        packages:
        - g++-4.9
        - binutils-avr
        - gcc-avr-4.9
        - avr-libc
        - avrdude
        sources:
        - ubuntu-toolchain-r-test
script:
  - uname
  - which avr-gcc && avr-gcc --version
